app/routes/login.py
from flask import (
    render_template,
    Blueprint,
    session,
    request,
    redirect,
    g
)
import re, secrets
from app.classes.user import User
from app.helpers.wrappers import get_logged_in_user
from urllib.parse import unquote

auth = Blueprint('auth', __name__)

class AuthError(Exception):
    pass


@auth.before_request
def auth_before_request():
    """ disallow these endpoints from being accessed if the user is logged in """
    v = get_logged_in_user()

    if v:
        redirect_to = request.args.get('redirect', '/')
        redirect_to = unquote(redirect_to)

        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)


@auth.get('/c/login')
def login_get():

    redirect_to = request.args.get('redirect', '/')
    redirect_to = unquote(redirect_to)

    if not redirect_to.startswith('/'):
        redirect_to = '/'

    return render_template("login.html", redirect=redirect_to)


@auth.post('/c/login')
def login_post():

    try:
        username = request.form.get('name', '').strip()
        password = request.form.get('password', '').strip()
        redirect_to = request.form.get('redirect', '/')

        if not username or not password:
            raise AuthError()

        user = g.db.query(User).filter(User.name.ilike(username)).first()
        if not user:
            raise AuthError()

        if not user.check_password(password):
            raise AuthError()

        session['user_id'] = user.id
        session['login_nonce'] = user.login_nonce
        session['session_id'] = secrets.token_hex(16)

        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)

    except AuthError as e:
        return render_template('login.html', error="invalid username/password")


@auth.post('/c/register')
def signup():

    try:
        username = request.form.get('name', '').strip()
        password = request.form.get('password', '').strip()
        redirect_to = request.form.get('redirect', '/')

        if not username or not password:
            raise AuthError("invalid username/password")

        valid_name_regex = re.compile('^[a-zA-Z0-9_]{3,20}$')
        if not valid_name_regex.fullmatch(username):
            raise AuthError("username must be 3-20 characters long and cannot contain special characters")

        if len(password) < 3:
            raise AuthError("password must be at least 3 characters long")

        existing_user = g.db.query(User).filter(User.name.ilike(username)).first()
        if existing_user:
            raise AuthError("username already taken")

        new_user = User(
            name=username,
            password=password,
            creation_ip=request.remote_addr,
            post_anon=('anon' in request.form)
        )

        g.db.add(new_user)
        g.db.flush()

        session['user_id'] = new_user.id
        session['login_nonce'] = new_user.login_nonce
        session['session_id'] = secrets.token_hex(16)

        # don't allow redirect to other sites the spaghetti way
        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)

    except AuthError as e:
        return render_template('login.html', error=str(e))

app/routes/posts.py
from flask import (
	Blueprint,
	render_template,
	redirect,
	request,
	abort,
	url_for
)
from app.classes.post import *
from app.classes.report import *
from app.helpers.wrappers import *
from app.helpers.get import *
from app.helpers.parser import *
import os
import time
import shutil
from werkzeug.utils import secure_filename
from app.__main__ import app

posts_blueprint = Blueprint('posts_blueprint', __name__)

class PostException(Exception):
	pass


def truncate(text):
	r = text[0:10]
	if len(text) > 10:
		r += "... "

	return r


@posts_blueprint.get('/*/post/<pid>')
def get_post_by_id(pid):

	post = get_post(pid)
	if not post:
		abort(404)

	return redirect(post.permalink)


@posts_blueprint.get('/<boardname>/post/<pid>')
def board_post_by_id(boardname, pid):

	post = get_post(pid)
	if not post or post.board.name != boardname:
		abort(404)

	return redirect(post.permalink)


@posts_blueprint.get('/<boardname>/post/<pid>/report')
@auth_required
def report_post(boardname, pid):

	post = get_post(pid)
	if not post or post.board.name != boardname:
		abort(404)

	return render_template(
		'boards/report.html',
		post=post,
		v=g.v
	)


@posts_blueprint.post('/post/<pid>/report')
@auth_required
def submit_report(pid):

	post = get_post(pid)
	if not post:
		abort(404)

	existing_report = g.db.query(Report).filter(
		Report.user_id == g.v.id,
		Report.post_id == post.id).first()

	if existing_report:
		return render_template(
			'message.html',
			title="you already reported this post",
			message="Find something else to cry about already.",
			v=g.v
		), 409

	reason = request.form.get("reason", "")
	if len(reason) < 5:
		return render_template(
			'message.html',
			title="report reason too short",
			message="Please write an essay on why this exact post makes you so mad.",
			v=g.v
		), 403

	if len(reason) > 255:
		return render_template(
			'message.html',
			title="WORDS WORDS WORDS WORDS WORDS",
			message="shut the fuck up nigga",
			v=g.v
		), 413

	if not post.approved:
		report = Report(
			post_id=post.id,
			user_id=g.v.id,
			creation_ip=request.remote_addr,
			reason=reason
		)

		g.db.add(report)

	return render_template(
		'message.html',
		title="report submitted",
		message="You may now leave this page.",
		v=g.v
	), 403


@posts_blueprint.get('/<boardname>/thread/<pid>')
@auth_desired
def get_post_view(boardname, pid):

	boardname = boardname.lower()
	post = get_post(pid)

	if not post:
		abort(404)

	if post.board.name != boardname:
		return redirect(post.permalink)

	b = post.board
	mod = False
	if g.v:
		mod = b.get_mod(g.v)

	if mod:
		perm_users = mod.perm_users
	else:
		perm_users = False

	mod_view = mod and mod.perm_content and 'mod' in request.args

	replies = post.reply_listing(mod=mod_view)

	return render_template(
		'boards/post.html',
		board=b,
		post=post,
		replies=replies,
		v=g.v,
		reveal_names=perm_users,
		mod=mod,
		mod_view=mod_view
	)


@posts_blueprint.post("/<boardname>/submit")
@posts_blueprint.post("/<boardname>/thread/<pid>/reply")
@auth_required
def submit(boardname, pid = None):

	try:

		board = get_board(boardname)
		if not board:
			raise PostException("invalid board")

		ban = board.get_ban(g.v)
		if not g.v.admin and not board.has_mod(g.v) and ban:

			post = get_post(ban.banned_for)

			return render_template(
				'errors/banned.html',
				ban=ban,
				board=board,
				post=post,
				v=g.v
			)

		options = [x.strip() for x in request.form.get("options").strip().split()]
		anon = g.v.post_anon or "anon" in options
		title = request.form.get("title", "")
		body = request.form.get("body", "")

		if not title and not pid:
			raise PostException("a title is required for top-level threads")

		if len(title) > 50:
			raise PostException("title must be shorter than 50 characters")

		if len(body) < 2:
			raise PostException("body too short")

		if len(body) > 10000:
			raise PostException("body too long")

		if pid:
			parent = get_post(pid)
			title = ""
			if not parent:
				raise PostException("the post you're replying to has been deleted")

			if parent.archived and not board.has_mod(g.v):
				raise PostException("this post is archived. you cannot reply anymore.")

			if 'sage' not in options:
				parent.last_bump_utc = int(time.time())
				g.db.add(parent)

		mod = 'mod' in options and board.has_mod(g.v)

		new_post = Post(
			title=title,
			anon=anon,
			body=body,
			creation_ip=request.remote_addr,
			author_id=g.v.id,
			parent_id=pid,
			board_id=board.id,
			mod=mod
		)

		if not pid:
			new_post.last_bump_utc = int(time.time())

		g.db.add(new_post)
		g.db.flush()

		"""
		take care of attachments.
		attachments are saved to `/_static/ugc/thread/<parent id>/<post id>/<file name>`
		for top-level posts, the parent id is the same as its own id
		"""
		file = request.files.get("file")
		if file and file.mimetype.startswith(('image/', 'audio/', 'video/', 'application/pdf')):

			parent_id = str(pid if pid else new_post.id)
			path = os.path.join('./app/_static/ugc/thread', parent_id)
			path = os.path.join(path, str(new_post.id))
			# create directories
			os.makedirs(path, exist_ok=True)

			filename = secure_filename(file.filename)
			dirname = os.path.join(path, filename)
			extension = filename.split('.')[-1]

			file.save(dirname)
			new_post.attachment_url = url_for(
				'static_blueprint.get_post_file',
				parent_id=parent_id,
				pid=str(new_post.id),
				filename=filename
			)
			new_post.attachment_size = request.content_length // 1024
			new_post.attachment_type = extension.upper()
			new_post.attachment_name = truncate(".".join(filename.split('.')[:-1])) + '.' + extension
			new_post.attachment_mimetype = file.mimetype

		if pid:
			context = new_post
		else:
			context = None

		body_html = parse(body, context=context)
		new_post.body_html = body_html

		g.db.add(new_post)
		g.db.flush()

		return redirect(new_post.permalink)

	except PostException as e:
		return str(e), 400


@posts_blueprint.post('/<boardname>/post/<pid>/delete')
@auth_required
@mod_required('content')
def mod_delete_post(board, pid):

	post = get_post(pid)

	if not post:
		abort(404)

	if post.board_id != board.id:
		abort(400)

	if request.referrer.endswith('?mod'):
		redirect_to = board.permalink if post.is_top_level else post.parent.permalink+'?mod'
	else:
		redirect_to = request.referrer

	# delete files
	path = os.path.join(app.static_folder, 'ugc/thread')
	if post.is_top_level:
		path = os.path.join(path, str(post.id))
	else:
		path = os.path.join(path, str(post.parent_id))
		path = os.path.join(path, str(post.id))

	if os.path.exists(path):
		shutil.rmtree(path, ignore_errors=True)

	if post.is_top_level:
		for p in post.replies:

			for r in p.reports:
				g.db.delete(r)

			g.db.delete(p)

	for r in post.reports:
		g.db.delete(r)

	g.db.delete(post)

	return redirect(redirect_to)


@posts_blueprint.post('/<boardname>/thread/<pid>/options')
@auth_required
@mod_required('content')
def mod_update_post(board, pid):

	post = get_post(pid)

	if not post:
		abort(404)

	if post.board_id != board.id:
		abort(400)

	post.archived = 'archive' in request.form
	pin = 'sticky' in request.form

	# replace previous sticky
	if pin:
		prev = g.db.query(Post).filter_by(board_id=board.id, pinned=True).first()
		if prev:
			prev.pinned = False
			g.db.add(prev)

	post.pinned = pin

	return redirect(post.permalink+'?mod')


@posts_blueprint.post('/<boardname>/post/<pid>/close_reports')
@auth_required
@mod_required("content")
def mod_close_reports(board, pid):

	post = get_post(pid)

	if not post:
		abort(404)

	if post.board_id != board.id:
		abort(400)

	for report in post.reports:
		g.db.delete(report)

	return redirect(request.referrer)


@posts_blueprint.post('/<boardname>/post/<pid>/approve')
@auth_required
@mod_required("content")
def mod_approve(board, pid):

	post = get_post(pid)

	if not post:
		abort(404)

	if post.board_id != board.id:
		abort(400)

	for report in post.reports:
		g.db.delete(report)

	post.approved = True
	g.db.add(post)

	return redirect(request.referrer)


@posts_blueprint.post('/<boardname>/post/<pid>/unapprove')
@auth_required
@mod_required("content")
def mod_unapprove(board, pid):

	post = get_post(pid)

	if not post:
		abort(404)

	if post.board_id != board.id:
		abort(400)

	post.approved = False
	g.db.add(post)

	return redirect(request.referrer)

app/routes/settings.py
from flask import (
	Blueprint,
	request,
	g,
	session,
	render_template,
	abort
)
from app.helpers.wrappers import get_logged_in_user

settings = Blueprint('settings', __name__, url_prefix='/c/settings')


@settings.before_request
def settings_before_request():
	""" these endpoints all require a logged in account """
	v = get_logged_in_user()

	if not v:
		abort(401)

	g.v = v


@settings.get('/')
def settings_index():

	return render_template('settings/index.html', v=g.v)


@settings.post('/logout_everywhere')
def logout_everywhere():

	# confirm password
	if not g.v.check_password(request.form.get('password', '')):
		return render_template(
			'settings/index.html',
			error='invalid password',
			v=g.v
		)

	# increment login nonce
	g.v.login_nonce += 1

	session.pop('user_id')
	session.pop('login_nonce')

	return render_template(
		'message.html',
		title='action successful',
		message='you have been logged out everywhere.'
	)

app/routes/user.py
from flask import Blueprint, request, render_template
from app.helpers.wrappers import *

user_blueprint = Blueprint('user_blueprint', __name__)
""" these do not always require a logged in accout """


@user_blueprint.get('/my_info')
@auth_required
def my_info():

	v = g.v

	hide_fields = (
		'passhash',
		'_sa_instance_state'
	)

	data = {key:value for key, value in v.__dict__.items() if key not in hide_fields}
	data['_banned'] = bool(data['_banned'])

	return render_template('user/my_info.html', data=data, v=v)

app/templates/components/attachment.html
<div class="attachment-wrapper">
	<div class="attachment">
		<a class="attachment-link" {% if post.attachment_mimetype.startswith('image/') %}href="{{ post.attachment_url }}" target="_blank"{% else %}href="javascript:void()"{% endif %}>
			{% if post.attachment_mimetype.startswith('image/') %}
				 <div class="image-wrap">
				 	<img src="{{ post.attachment_url }}" loading="lazy" />
				 </div>
			{% elif post.attachment_mimetype.startswith('audio/') %}
				<audio controls src="{{ post.attachment_url }}">
					Unsupported file type :(
				</audio>
			{% elif post.attachment_mimetype.startswith('video/') %}
				<video controls width="250">
					<source src="{{ post.attachment_url }}" type="{{ post.attachment_mimetype }}">
					Unsupported file type :(
				</video>
			{% endif %}
		</a>
		{% if post.attachment_mimetype == "application/pdf" %}
			<div class="pdf-wrapper">
				<h4>{{ post.attachment_name }}</h4>
				<a href="{{ post.attachment_url }}" target="_blank">Open in PDF viewer</a>
			</div>
		{% endif %}
		<div class="attachment-details">
			<a class="attachment-download" href="{{ post.attachment_url }}?download">{{ post.attachment_name }}</a>
			<div class="attachment-info">
				{{ post.attachment_size }}KB {{ post.attachment_type }}
			</div>
		</div>
	</div>
</div>

app/templates/components/header.html
<nav style="background-color: {{ 'SITE_COLOR' | app_config  }};">
    <div class="grid-container">
        <div id="nav-links">
            <a href="/">Home</a>
            <a href="/*/">Overboard</a>
            <a href="{{ url_for('boards.get_create') }}">Create board</a>
        </div>
        <div id="nav-account">
            {% if v %}
            <a href="{{ url_for('user_blueprint.my_info') }}">{{ v.name }}</a> 
            |
            <a href="{{ url_for('settings.settings_index') }}">settings</a> 
            |
            <form id="logout" class="inline-form" action="{{ url_for('logout') }}" method="post">
                <input type="submit" value="logout" />
            </form>
            {% else %}
            [ <a href="{{ url_for('auth.login_get') }}">login / register</a> ]
            {% endif %}
        </div>
    </div>
</nav>

app/templates/components/post_header.html
<div class="post-info">
	{% if bulk_actions %}
		<span class="post-detail post-checkbox">
			<input type="checkbox" name="{{ post.id }}" />
		</span>
	{% endif %}
	{% if post.pinned %}
		<span class="post-detail post-pinned">
			<strong class="green">[pinned]</strong>
		</span>
	{% endif %}
	<span class="post-detail post-title">
		<strong>{{ post.title }}</strong>
	</span>
	<span class="post-detail post-author">
		<span class="post-info-author">
			<strong class="{% if post.mod %}mod{% elif post.anon %}anon{% else %}author{% endif %}">
				{% if post.anon and not reveal_names %}
					Anonymous
				{% else %}
					{{ post.author.name }}
				{% endif %}
				{% if post.mod %}
					# mod
				{% endif %}
			</strong>
			{% if post.anon and reveal_names %}
				<span class="green" title="anonymous post, but you can see the username because you mod this board">
					[hidden]
				</span>
			{% endif %}
		</span>
	</span>
	<span class="post-detail post-age">
		{{ post.created_string }}
	</span>
	<span class="post-detail post-id">
		<a href="#{{ post.id }}">No.</a><a href="#{{ post.id }}">{{ post.id }}</a>
	</span>
	{% if mod and post.approved %}
		<span class="green" title="this post no longer accepts reports">
			approved
		</span>
	{% endif %}
	{% if (listing and post.is_top_level) or show_thread_link %}
		<span class="post-detail post-link">
			[
				<a href="{{ post.permalink }}">View thread</a>
			]
		</span>
	{% endif %}
	{% if board and v %}
		<div class="post-detail post-actions">
			<div class="actions-anchor">
				<span class="actions-label">
					&#9660;
				</span>
				<div class="actions">
					<a class="action action-report" href="{{ url_for('posts_blueprint.report_post', boardname=board.name, pid=post.id) }}" target="_blank">Report</a>
					<a class="action action-report-global" href="" target="_blank">Report Globally</a>
					{% if mod and mod.perm_users %}
						<a class="action action-ban" href="{{ url_for('boards.ban_for', boardname=board.name, pid=post.id) }}" target="_blank">Ban user from /{{ board.name }}/</a>
						<a class="action action-history" href="{{ url_for('boards.board_user_history', boardname=board.name, pid=post.id) }}" target="_blank">User history in /{{ board.name }}/</a>
					{% endif %}
				</div>
			</div>
		</div>
	{% endif %}
	<span class="post-detail quoted-by">
		{% for p in post.quoted_by %}
			{% if listing %}
				<a href="{{ post.no_anchor_link }}#{{ p }}">>>{{ p }}</a>
			{% else %}
				<a href="#{{ p }}">>>{{ p }}</a>
			{% endif %}
		{% endfor %}
	</span>
</div>

app/templates/components/post_listing.html
{% set listing=True %}
{% for post in posts %}
	<div id="thread-{{ post.id }}" class="thread">
		{% if not board %}
			<h3><a href="{{ post.board.permalink }}">/{{ post.board.name }}/{% if post.board.title %}: {{ post.board.title }}{% endif %}</a></h3>
		{% endif %}
		<div class="post" id="{{ post.id }}">
			<span class="wingding">
				<span class="no-mobile">>></span>
			</span>
			{% include "components/post_header.html" %}
			{% if post.attachment_url %}
				{% include "components/attachment.html" %}
			{% endif %}
			<blockquote class="post ugc">
				{{ post.body_html | markdown }}
			</blockquote>
		</div>
		{% for post in post.preview_replies() %}
			{% include "components/reply.html" %}
		{% endfor %}
	</div>
{% endfor %}

app/templates/components/reply.html
<div class="post post-reply" id="{{ post.id }}">
	<span class="wingding">
		<span class="no-mobile">
			>>
		</span>
	</span>
	<div class="reply-container">
		{% include "components/post_header.html" %}
		{% if post.attachment_url %}
			{% include "components/attachment.html" %}
		{% endif %}
		<blockquote class="post ugc">
			{{ post.body_html | markdown }}
		</blockquote>
		{% if post.banned_for %}
			<h4 class="red banned-for">(USER WAS BANNED FOR THIS POST)</h4>
		{% endif %}
		{% if mod_view %}
			<div class="mod-reply">
				<form action="{{ url_for('posts_blueprint.mod_delete_post', boardname=board.name, pid=post.id) }}" method="post">
					<input type="submit" class="btn btn-danger" value="delete" />
				</form>
				{% if post.reports %}
					<form action="{{ url_for('posts_blueprint.mod_close_reports', boardname=board.name, pid=post.id) }}" method="post">
						<input type="submit" class="btn btn-gray" value="close reports" />
					</form>
					<form action="{{ url_for('posts_blueprint.mod_approve', boardname=board.name, pid=post.id) }}" method="post">
						<input type="submit" class="btn btn-success" value="approve" />
					</form>
				{% elif post.approved %}
					<form action="{{ url_for('posts_blueprint.mod_unapprove', boardname=board.name, pid=post.id) }}" method="post">
						<input type="submit" class="btn btn-danger" value="unapprove" />
					</form>
				{% endif %}
			</div>
		{% endif %}
		{% if mod_view and post.reports %}
			<div class="report-list">
				<details>
					<summary>view reports</summary>
					<ul>
						{% for report in post.reports %}
							<li>{{ report.reason }}
						{% endfor %}
					</ul>
				</details>
			</div>
		{% endif %}
	</div>
</div>