app/routes/boards.py
from flask import (
	Blueprint,
	request,
	render_template,
	g,
	redirect,
	abort,
	url_for
)
from app.helpers.wrappers import *
from app.classes.board import *
from app.classes.board_relationships import *
from app.helpers.get import get_board
from app.__main__ import app
import re, time, os, shutil

boards = Blueprint('boards', __name__)
valid_name_regex = re.compile('^[a-zA-Z0-9-_]{3,20}$')



def overboard_listing(page=1, limit=25, query=None):

	posts = g.db.query(Post).filter(Post.parent_id == None)

	posts = posts.order_by(Post.created_utc.desc())

	if query:
		# escape pqsl wildcards
		query = query.replace('%', '\%')
		query = query.replace('_', '\_')

		posts = posts.filter(or_(
			Post.title.ilike(f'%{query}%'),
			Post.body_html.ilike(f'%{query}%')
			)
		)

	has_next = posts.count() > page*limit

	return (posts.offset(limit * (page - 1)).limit(limit).all(), has_next)


class BoardError(Exception):
	pass


def can_make_board(user) -> bool:

	if user.admin:
		return True

	created_board_recently = bool(g.db.query(Board).filter(
		Board.creator_id == user.id,
		Board.created_utc > int(time.time()) - 60*60*24*3).first())

	return not created_board_recently


@boards.get('/c/create')
@auth_required
def get_create():

	return render_template('boards/create.html', v=g.v)


@boards.post('/c/create')
@auth_required
def post_create():

	try:
		name = request.form.get("name", "")
		name = name.strip().lower()
		if not valid_name_regex.fullmatch(name) or name == "c":
			raise BoardError("invalid name")

		# check if board already exists
		already_exists = bool(g.db.query(Board).filter_by(name=name).first())
		if already_exists:
			raise BoardError("a board with that name already exists")

		title = request.form.get("title", "")
		if len(title) > 20:
			raise BoardError("title must be shorter than 20 characters")

		desc = request.form.get("desc", "")
		if len(desc) > 255:
			raise BoardError("description cannot be longer than 255 characters")

		if not can_make_board(g.v):
			raise BoardError("you can only make one board every 3 days")

		new_board = Board(
			name=name,
			title=title,
			description=desc,
			creation_ip=request.remote_addr,
			creator_id=g.v.id
		)

		g.db.add(new_board)
		g.db.flush()

		mod_rel = ModRelationship(
			user_id=g.v.id,
			board_id=new_board.id
		)

		g.db.add(mod_rel)

		return redirect(new_board.permalink)

	except BoardError as e:
		return render_template('boards/create.html', v=g.v, error=str(e)), 400


@boards.get('/*/')
@auth_desired
def overboard():

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)

	listing = overboard_listing(page=page, limit=limit)
	posts = listing[0]
	has_next = listing[1]

	return render_template(
		'boards/index.html',
		v=g.v,
		posts=posts,
		has_next=has_next,
		page=page,
		limit=limit
	)


@boards.get('/*/catalog')
@auth_desired
def overboard_catalog():

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)
	query = request.args.get("filter")

	listing = overboard_listing(page=page, limit=limit, query=query)
	posts = listing[0]
	has_next = listing[1]

	return render_template(
		'boards/catalog.html',
		v=g.v,
		posts=posts,
		has_next=has_next,
		page=page,
		limit=limit,
		query=query
	)


@boards.get('/<name>/')
@auth_desired
def get_board_page(name):

	b = get_board(name)
	if not b:
		abort(404)

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)

	listing = b.get_listing(page=page, limit=limit)
	posts = listing[0]
	has_next = listing[1]

	mod = False
	if g.v:
		mod = b.get_mod(g.v)

	if mod:
		reveal_names = mod.perm_users
	else:
		reveal_names = False

	return render_template(
		'boards/index.html',
		v=g.v,
		board=b,
		posts=posts,
		has_next=has_next,
		page=page,
		limit=limit,
		mod=mod,
		reveal_names=reveal_names
	)


@boards.get('/<name>/catalog')
@auth_desired
def get_board_catalog(name):

	b = get_board(name)
	if not b:
		abort(404)

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)
	query = request.args.get("filter")

	listing = b.get_listing(page=page, limit=limit, query=query)
	posts = listing[0]
	has_next = listing[1]

	return render_template(
		'boards/catalog.html',
		v=g.v,
		board=b,
		posts=posts,
		has_next=has_next,
		page=page,
		limit=limit,
		query=query
	)


@boards.get('/<name>/mod')
@auth_required
def board_mod(name):

	b = get_board(name)
	if not b:
		abort(404)

	mod = b.get_mod(g.v)
	if not mod:
		abort(403)

	return render_template(
		'boards/mod_settings.html',
		v=g.v,
		board=b,
		mod=mod
	)


@boards.get('/<boardname>/mod/reports')
@auth_required
@mod_required("content")
def board_reports(board):

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)

	posts = g.db.query(Post).filter_by(board_id=board.id).\
		options(joinedload(Post.reports)).\
		join(Report, Post.id == Report.post_id).\
		filter(Report.is_global == False)

	has_next = posts.count() > page*limit

	mod = board.get_mod(g.v)

	return render_template(
		'boards/listing.html',
		v=g.v,
		board=board,
		posts=posts.offset(limit * (page-1)).limit(limit).all(),
		has_next=has_next,
		page=page,
		limit=limit,
		mod_view=True,
		mod=mod,
		reveal_names=mod.perm_users,
		title="Reported posts",
		show_thread_link=True
	)


@boards.get('/<boardname>/mod/approved')
@auth_required
@mod_required("content")
def board_approved(board):

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)

	posts = g.db.query(Post).filter_by(board_id=board.id, approved=True)

	has_next = posts.count() > page*limit

	mod = board.get_mod(g.v)

	return render_template(
		'boards/listing.html',
		v=g.v,
		board=board,
		posts=posts.offset(limit * (page-1)).limit(limit).all(),
		has_next=has_next,
		page=page,
		limit=limit,
		mod_view=True,
		mod=mod,
		reveal_names=mod.perm_users,
		title="Approved posts",
		show_thread_link=True
	)


@boards.get('/<boardname>/post/<pid>/history')
@auth_required
@mod_required("users")
def board_user_history(board, pid):

	page = int(request.args.get("page", 1))
	limit = min(int(request.args.get("limit", 25)), 200)

	p = get_post(pid)
	if not p:
		abort(404)

	user = p.author

	posts = g.db.query(Post).filter_by(board_id=board.id, author_id=user.id)

	has_next = posts.count() > page*limit

	mod = board.get_mod(g.v)

	return render_template(
		'boards/listing.html',
		v=g.v,
		board=board,
		posts=posts.offset(limit * (page-1)).limit(limit).all(),
		has_next=has_next,
		page=page,
		limit=limit,
		mod_view=True,
		mod=mod,
		reveal_names=True,
		title="User history",
		show_thread_link=True,
		history_for=pid
	)


@boards.post('/<boardname>/post/<pid>/purge_history')
@auth_required
@mod_required("users")
def board_purge_history(board, pid):

	p = get_post(pid)
	if not p:
		abort(404)

	user = p.author
	posts = g.db.query(Post).filter_by(board_id=board.id, author_id=user.id)

	for post in posts:
		# delete files
		path = os.path.join(app.static_folder, 'ugc/thread')
		if post.is_top_level:
			path = os.path.join(path, str(post.id))
		else:
			path = os.path.join(path, str(post.parent_id))
			path = os.path.join(path, str(post.id))

		if os.path.exists(path):
			shutil.rmtree(path, ignore_errors=True)

		if post.is_top_level:
			for p in post.replies:

				for r in p.reports:
					g.db.delete(r)

				g.db.delete(p)

		for r in post.reports:
			g.db.delete(r)

		g.db.delete(post)

	return render_template(
		'message.html',
		v=g.v,
		title='user history purged',
		message='deleted all posts, replies and files from this user'
	)


@boards.get('/<boardname>/mod/mods')
@auth_desired
def board_mods(boardname, error=None):

	board = get_board(boardname)
	if not board:
		abort(404)

	mods = g.db.query(ModRelationship).filter_by(board_id=board.id).options(joinedload(ModRelationship.user))
	mods = mods.order_by(ModRelationship.mod_level.asc())

	if g.v:
		mod = board.get_mod(g.v)
	else:
		mod = None

	code = 400 if error else 200

	return render_template(
		'boards/mods.html',
		v=g.v,
		board=board,
		mods=mods,
		mod=mod,
		perms=ModRelationship.permissions(),
		error=error
	), code


@boards.post('/<boardname>/mod/add')
@auth_required
@mod_required("full")
def add_mod(board):

	try:
		u = get_user(request.form.get("user", ""))
		if not u:
			raise BoardError("user doesn't exist")

		if u._banned and not u.unban_utc:
			raise BoardError(f"{u.name} is permanently banned")

		if board.has_mod(u):
			raise BoardError(f"{u.name} is already a mod of /{board.name}/")

		if board.has_ban(u):
			raise BoardError(f"{u.name} is banned from /{board.name}/")
	except BoardError as e:
		return board_mods(board.name, error=str(e))

	_permissions = ModRelationship.permissions()
	new_perms = {}
	for p in _permissions:
		new_perms[p] = p in request.form

	last_mod_level = g.db.query(ModRelationship)\
		.filter_by(board_id=board.id)\
		.order_by(ModRelationship.mod_level.desc())\
		.first()\
		.mod_level

	new_mod = ModRelationship(
		board_id=board.id,
		user_id=u.id,
		mod_level=last_mod_level+1,
		**new_perms
	)

	g.db.add(new_mod)
	g.db.commit()

	return redirect(url_for('boards.board_mods', boardname=board.name))


@boards.post('/<boardname>/mod/remove/<mod_id>')
@auth_required
@mod_required("full")
def remove_mod(board, mod_id):

	v_mod = board.get_mod(g.v)

	try:
		mod = g.db.query(ModRelationship).filter_by(id=mod_id).first()
		if not mod:
			raise BoardError(f"that user is not a mod of /{board.name}/")

		can_remove = mod.mod_level > v_mod.mod_level or mod.user_id == g.v.id
		if not can_remove:
			raise BoardError("you cannot remove that mod")

	except BoardError as e:
		return board_mods(board.name, error=str(e))

	lower_mods = g.db.query(ModRelationship).filter(
		ModRelationship.board_id == board.id,
		ModRelationship.mod_level<mod.mod_level).all()

	for m in lower_mods:
		m.mod_level -= 1

app/templates/boards/ban.html
{% extends "index.html" %}
{% block title %}Ban user{% endblock %}
{% block content %}
	<h2>Ban <code>{{ post.author.name }}</code></h2>
	<form class="form" action="{{ url_for('boards.ban_from_board', boardname=post.board.name) }}" method="post">
		<input type="hidden" name="target" value="{{ post.author.name }}" />
		<input type="hidden" name="post" value="{{ post.id }}" />
		<div class="form-entry">
			<label for="reason">reason for ban:</label>
			<input type="text" name="reason" required maxlength="255" class="form-input" placeholder="ban reason" />
		</div>
		<div class="form-entry">
			<label for="target">duration days (blank for permanent ban):</label>
			<input type="number" name="expiry" class="form-input" placeholder="days until the ban expires" />
		</div>
		<div class="form-entry">
			<input type="submit" class="btn btn-danger" value="ban user" />
		</div>
	</form>
	<h3>Banning user for:</h3>
	{% include "components/reply.html" %}
{% endblock %}

app/templates/boards/bans.html
{% extends "index.html" %}
{% block title %}users banned from /{{ board.name }}/{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	<div class="board-links">
		<a class="btn link-btn" href="{{ url_for('boards.get_board_page', name=board.name) }}">Index</a>
		<a class="btn link-btn" href="{{ url_for('boards.board_mod', name=board.name) }}">Back to mod tools</a>
	</div>
	<form class="form" action="{{ url_for('boards.ban_from_board', boardname=board.name) }}" method="post">
		<div class="form-entry">
			<label for="target">username:</label>
			<input type="text" name="target" required maxlength="25" class="form-input" placeholder="username or IP" />
		</div>
		<div class="form-entry">
			<label for="reason">reason for ban:</label>
			<input type="text" name="reason" required maxlength="255" class="form-input" placeholder="ban reason" />
		</div>
		<div class="form-entry">
			<label for="target">offending post ID:</label>
			<input type="number" name="post" required maxlength="25" class="form-input" placeholder="ID of post to ban the user for" />
		</div>
		<div class="form-entry">
			<label for="target">duration days (blank for permanent ban):</label>
			<input type="number" name="expiry" class="form-input" placeholder="days until the ban expires" />
		</div>
		<div class="form-entry">
			<input type="submit" class="btn btn-danger" value="ban user" />
		</div>
	</form>
	{% if bans %}
		<h3>bans in /{{ board.name }}/</h3>
		<table class="user-listing">
			<thead>
				<tr>
					<th>user</th>
					<th>banned by</th>
					<th>banned for</th>
					<th>expires</th>
					<th>reason</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% for ban in bans %}
					<tr>
						<td>{{ ban.user.name }}</td>
						<td>{{ ban.banning_mod.name }}</td>
						<td><a target="_blank" class="post-mention" href="/*/post/{{ ban.banned_for }}">>>{{ ban.banned_for }}</a></td>
						<td {% if ban.expires_utc > 0 %}title="{{ ban.expires }}"{% endif %}>
							{% if ban.expires_utc > 0 %}
								{% if ban.duration_days > 1 %}
									in {{ ban.duration_days }} days
								{% else %}
									in a day
								{% endif %}
							{% else %}
								never
							{% endif %}
						</td>
						<td>{{ ban.ban_reason }}</td>
						<td>
							<form class="inline-form" action="{{ url_for('boards.unban_from_board', boardname=board.name) }}" method="post">
								<input type="hidden" name="id" value="{{ ban.id }}" />
								<input type="submit" value="unban" />
							</form>
						</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% endif %}
{% endblock %}

app/templates/boards/catalog.html
{% extends "index.html" %}
{% block title %}
	{% if board %}
		/{{ board.name }}/{% if board.title %}: {{ board.title }}{% endif %}
	{% else %}
		Overboard: All posts
	{% endif %}
{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	{% if board %}
		{% if v %}
			<div class="submit-wrapper">
				<div class="submit-form">
					<strong>New thread</strong>
					<form enctype="multipart/form-data" action="{{ url_for('posts_blueprint.submit', boardname=board.name) }}" method="post">
						<input type="text" class="field" name="options" placeholder="Options" />
						<input required maxlength="50" type="text" class="field" name="title" placeholder="Subject" />
						<textarea maxlength="10000" required name="body" cols="50" rows="3" class="field"></textarea>
						<span class="file-field">
							<input type="file" name="file" accept="image/*, audio/*, video/*, application/pdf" />
						</span>
						<input type="submit" class="field" value="Create thread" />
					</form>
				</div>
			</div>
		{% endif %}
	{% endif %}
	<div class="board-links">
		<a class="btn link-btn" href="{% if board %}{{ url_for('boards.get_board_page', name=board.name) }}{% else %}{{ url_for('boards.overboard') }}{% endif %}">Index</a>
		<form class="cat-search">
			<input class="form-input" type="search" name="filter" placeholder="enter search text" {% if query %}value="{{ query }}"{% endif %} />
			<input type="submit" value="search" class="btn link-btn" />
		</form>
	</div>
	<div class="catalog-container">
		{% for post in posts %}
			<div class="thread-card">
				<div class="post-card">
					{% if not board %}
						<h3><a href="{{ post.board.permalink }}">/{{ post.board.name }}/{% if post.board.title %}: {{ post.board.title }}{% endif %}</a></h3>
					{% endif %}
					<h3>R: {{ post.comment_count }} / Q: {{ post.quote_count }}</h3>
					{% if post.attachment_url %}
						{% include "components/attachment.html" %}
					{% endif %}
					<div class="post-card-content">
						<strong class="post-card-title"><a href="{{ post.permalink }}">{{ post.title }}</a></strong>
						<blockquote class="post-card-body ugc">
							{{ post.body_html | markdown }}
						</blockquote>
					</div>
				</div>
			</div>
		{% endfor %}
	</div>
	<div class="footer">
		{% if posts %}
			<a class="btn link-btn" href="#">back to top</a>
			{% if page > 1 %}
				<a class="btn link-btn" href="?page={{ page-1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">< previous page</a>
			{% endif %}
			{% if has_next %}
				<a class="btn link-btn" href="?page={{ page+1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">next page ></a>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}

app/templates/boards/create.html
{% extends "index.html" %}
{% block title %}Create board{% endblock %}
{% block content %}

{% if error %}
	<h4 class="red">{{ error }}</h4>
{% endif %}

<form class="form" action="{{ url_for('boards.post_create') }}" method="post">
	<h2>Create board</h2>
	<div class="form-entry">
		<label for="name">board name: <span class="red">*</span></label>
		<input type="text" name="name" required placeholder="enter board name">
		<p class="hint">must be between 3-20 characters and cannot contain special characters</p>
	</div>
	<div class="form-entry">
		<label for="title">board title:</label>
		<input type="text" name="title" placeholder="enter board title">
	</div>
	<div class="form-entry">
		<label for="desc">board description:</label>
		<textarea rows="5" name="desc" placeholder="enter board description"></textarea>
	</div>
	<div class="form-entry">
		<input type="submit" value="create" />
	</div>
</form>

<p class="hint">required fields are marked with <strong class="red">*</strong></p>

{% endblock %}

app/templates/boards/header.html
<div class="board-header">
	{% if board %}
		<h1>/{{ board.name }}/{% if board.title %}: {{ board.title }}{% endif %}</h1>
		{% if board.description %}
			<p class="desc">{{ board.description }}</p>
		{% endif %}
	{% else %}
		<h1>Overboard: All posts</h1>
		<p class="desc">All posts from all boards, sorted by new.</p>
	{% endif %}
</div>

app/templates/boards/index.html
{% extends "index.html" %}
{% block title %}
	{% if board %}
		/{{ board.name }}/{% if board.title %}: {{ board.title }}{% endif %}
	{% else %}
		Overboard: All posts
	{% endif %}
{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	{% if board %}
		{% if v %}
			<div class="submit-wrapper">
				<div class="submit-form">
					<strong>New thread</strong>
					<form enctype="multipart/form-data" action="{{ url_for('posts_blueprint.submit', boardname=board.name) }}" method="post">
						<input type="text" class="field" name="options" placeholder="Options" />
						<input required maxlength="50" type="text" class="field" name="title" placeholder="Subject" />
						<textarea maxlength="10000" required name="body" cols="50" rows="3" class="field"></textarea>
						<span class="file-field">
							<input type="file" name="file" accept="image/*, audio/*, video/*, application/pdf" />
						</span>
						<input type="submit" class="field" value="Create thread" />
					</form>
				</div>
			</div>
		{% endif %}
	{% endif %}
	<div class="board-links">
		<a class="btn link-btn" href="{% if board %}{{ url_for('boards.get_board_catalog', name=board.name) }}{% else %}{{ url_for('boards.overboard_catalog') }}{% endif %}">Catalog</a>
		{% if mod %}
			<a class="btn link-btn" href="{{ url_for('boards.board_mod', name=board.name) }}">Settings</a>
		{% endif %}
	</div>
	<div class="threads">
		{% include "components/post_listing.html" %}
		{% if posts %}
			<div class="clear">
				<hr />
				<a class="btn link-btn" href="#">back to top</a>
				{% if page > 1 %}
					<a class="btn link-btn" href="?page={{ page-1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">< previous page</a>
				{% endif %}
				{% if has_next %}
					<a class="btn link-btn" href="?page={{ page+1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">next page ></a>
				{% endif %}
			</div>
		{% else %}
			<h4 class="red">dead {% if board %}board{% else %}site{% endif %} xd</h4>
		{% endif %}
	</div>
	{% if posts %}
		<hr />
	{% endif %}
{% endblock %}

app/templates/boards/listing.html
{% extends "index.html" %}
{% block title %}{{ title }} - /{{ board.name }}/{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	{% if history_for %}
	<div class="mod-box">
		<form action="{{ url_for('boards.board_purge_history', boardname=board.name, pid=history_for) }}" method="post">
			<input type="text" class="form-input" name="reason" placeholder="reason" />
			<input type="submit" class="btn btn-danger" value="bulk delete history" />
		</form>
	</div>
	{% endif %}
	<div class="board-links">
		<a class="btn link-btn" href="{{ url_for('boards.get_board_page', name=board.name) }}">Index</a>
		{% if mod %}
			<a class="btn link-btn" href="{{ url_for('boards.board_mod', name=board.name) }}">Back to mod tools</a>
		{% endif %}
	</div>
	<hr />
	{% if posts %}
		{% for post in posts %}
			{% include "components/reply.html" %}
		{% endfor %}
		<div class="footer">
			{% if posts %}
				<a class="btn link-btn" href="#">back to top</a>
				{% if page > 1 %}
					<a class="btn link-btn" href="?page={{ page-1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">< previous page</a>
				{% endif %}
				{% if has_next %}
					<a class="btn link-btn" href="?page={{ page+1 }}&limit={{ limit }}{% if query %}&filter={{ query }}{% endif %}">next page ></a>
				{% endif %}
			{% endif %}
		</div>
	{% else %}
		<h4 class="red">there doesn't seem to be anything here</h4>
	{% endif %}
{% endblock %}

app/templates/boards/mod_settings.html
{% extends "index.html" %}
{% block title %}/{{ board.name }}/ mod settings{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	<div class="board-links">
		<a class="btn link-btn" href="{{ url_for('boards.get_board_page', name=board.name) }}">Index</a>
	</div>
	{% if mod.perm_content %}
		<h2>Content</h2>
		<ul>
			<li>
				<a href="{{ url_for('boards.board_reports', boardname=board.name) }}">Reports</a>
			</li>
			<li>
				<a href="{{ url_for('boards.board_approved', boardname=board.name) }}">Approved posts</a>
			</li>
		</ul>
	{% endif %}
	<h2>Users</h2>
	<ul>
		{% if mod.perm_users %}
		<li>
			<a href="{{ url_for('boards.board_bans', boardname=board.name) }}">Banned users</a>
		</li>
		{% endif %}
		<li>
			<a href="{{ url_for('boards.board_mods', boardname=board.name) }}">Mods</a>
		</li>
	</ul>
{% endblock %}

app/templates/boards/mods.html
{% extends "index.html" %}
{% block title %}mods of /{{ board.name }}/{% endblock %}
{% block content %}
	{% include "boards/header.html" %}
	{% if mod %}
		<div class="mod-box">
			<form action="{{ url_for('boards.mod_resign', boardname=board.name) }}" method="post">
				<span>you're a mod of /{{ board.name }}/.</span>
				<input type="submit" class="btn btn-danger" value="resign" style="margin-left: 20px;" />
			</form>
		</div>
	{% endif %}
	{% if error %}
		<p class="red">{{ error }}</p>
	{% endif %}
	<div class="board-links">
		<a class="btn link-btn" href="{{ url_for('boards.get_board_page', name=board.name) }}">Index</a>
		{% if mod %}
			<a class="btn link-btn" href="{{ url_for('boards.board_mod', name=board.name) }}">Back to mod tools</a>
		{% endif %}
	</div>
	<hr />
	<table class="user-listing">
		<thead>
			<th>user</th>
			<th>added</th>
			<th>permissions</th>
			<th></th>
		</thead>
		<tbody>
			{% for m in mods %}
				<tr>
					<td>{{ m.user.name }}</td>
					<td title="{{ m.added }}">{{ m.created }}</td>
					<td>{{ m.perms_string }}</td>
					{% if mod and mod.perm_full and (m.mod_level>mod.mod_level) %}
						<td>
							<form class="inline-form" action="{{ url_for('boards.remove_mod', boardname=board.name, mod_id=m.id) }}" method="post">
								<input type="submit" value="remove mod" />
							</form>
						</td>
					{% endif %}
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% if mod and mod.perm_full %}
		<div class="add-mod-form">
			<h4>add mod</h4>
			<form action="{{ url_for('boards.add_mod', boardname=board.name) }}" method="post">
				<div>
					<input type="text" name="user" placeholder="username" maxlength="20" required />
					<input type="submit" class="btn link-btn" value="add mod" />
				</div>
				<div>
					<h5>permissions:</h5>
					{% for p in perms %}
						<div>
							<input type="checkbox" name="{{ p }}" checked />
							<label for="{{ p }}">{{ p | lstrip("perm_") }}</label>
						</div>
					{% endfor %}
				</div>
				<p class="hint">note: mods with full permissions will have access to all mod tools, regardless of other permissions</p>
			</form>
		</div>
	{% endif %}
{% endblock %}

app/templates/boards/report.html
{% extends "index.html" %}
{% block title %}Report post to board management{% endblock %}
{% block content %}
	<h2>Report post to moderators</h2>
	<form class="form" action="{{ url_for('posts_blueprint.submit_report', pid=post.id) }}" method="post">
		<div class="form-entry">
			<label for="reason">reason for reporting:</label>
			<textarea required rows="5" name="reason" placeholder="enter reason for reporting"></textarea>
		</div>
		<div class="form-entry">
			<input type="submit" class="btn link-btn" value="submit report" />
		</div>
	</form>
	<h3>Reporting:</h3>
	{% include "components/reply.html" %}
{% endblock %}