app/routes/login.py
from flask import (
    render_template,
    Blueprint,
    session,
    request,
    redirect,
    g
)
import re, secrets
from app.classes.user import User
from app.helpers.wrappers import get_logged_in_user
from urllib.parse import unquote

auth = Blueprint('auth', __name__)

class AuthError(Exception):
    pass


@auth.before_request
def auth_before_request():
    """ disallow these endpoints from being accessed if the user is logged in """
    v = get_logged_in_user()

    if v:
        redirect_to = request.args.get('redirect', '/')
        redirect_to = unquote(redirect_to)

        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)


@auth.get('/c/login')
def login_get():

    redirect_to = request.args.get('redirect', '/')
    redirect_to = unquote(redirect_to)

    if not redirect_to.startswith('/'):
        redirect_to = '/'

    return render_template("login.html", redirect=redirect_to)


@auth.post('/c/login')
def login_post():

    try:
        username = request.form.get('name', '').strip()
        password = request.form.get('password', '').strip()
        redirect_to = request.form.get('redirect', '/')

        if not username or not password:
            raise AuthError()

        user = g.db.query(User).filter(User.name.ilike(username)).first()
        if not user:
            raise AuthError()

        if not user.check_password(password):
            raise AuthError()

        session['user_id'] = user.id
        session['login_nonce'] = user.login_nonce
        session['session_id'] = secrets.token_hex(16)

        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)

    except AuthError as e:
        return render_template('login.html', error="invalid username/password")


@auth.post('/c/register')
def signup():

    try:
        username = request.form.get('name', '').strip()
        password = request.form.get('password', '').strip()
        redirect_to = request.form.get('redirect', '/')

        if not username or not password:
            raise AuthError("invalid username/password")

        valid_name_regex = re.compile('^[a-zA-Z0-9_]{3,20}$')
        if not valid_name_regex.fullmatch(username):
            raise AuthError("username must be 3-20 characters long and cannot contain special characters")

        if len(password) < 3:
            raise AuthError("password must be at least 3 characters long")

        existing_user = g.db.query(User).filter(User.name.ilike(username)).first()
        if existing_user:
            raise AuthError("username already taken")

        new_user = User(
            name=username,
            password=password,
            creation_ip=request.remote_addr,
            post_anon=('anon' in request.form)
        )

        g.db.add(new_user)
        g.db.flush()

        session['user_id'] = new_user.id
        session['login_nonce'] = new_user.login_nonce
        session['session_id'] = secrets.token_hex(16)

        # don't allow redirect to other sites the spaghetti way
        if not redirect_to.startswith('/'):
            redirect_to = '/'

        return redirect(redirect_to)

    except AuthError as e:
        return render_template('login.html', error=str(e))

app/templates/home.html
{% extends "index.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h2>Boards:</h2>
<ul>
    {% for b in boards %}
    <li>
        <a href="/{{ b.name }}/">/{{ b.name }}/</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/_static/css/light.css">
    {% block head %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include "components/header.html" %}
<div id="content">
    {% block content %}{% endblock %}
</div>
</body>
{% block script %}{% endblock %}
</html>

app/templates/login.html
{% extends "index.html" %}
{% block title %}log in or register{% endblock %}
{% block content %}
<div class="settings-wrapper">
  {% if error %}
  <h4 class="error">{{ error }}</h4>
  {% endif %}
  <div class="form-wrapper">
    <fieldset class="form-fieldset">
      <legend>Log in</legend>
      <form action="{{ url_for('auth.login_post') }}" method="post">
        <input type="hidden" name="redirect" value="{{ redirect }}" />
        <div>
          <label for="login-name">username: </label>
          <input type="text" id="login-name" name="name" required="" />
        </div>
        <br />
        <div>
          <label for="password">password: </label>
          <input type="password" id="login-password" name="password" required="" />
        </div>
        <br />
        <input type="submit" value="log in" class="form-submit" />
      </form>
    </fieldset>
    <fieldset class="form-fieldset">
      <legend>Register</legend>
      <form action="{{ url_for('auth.signup') }}" method="post">
        <input type="hidden" name="redirect" value="{{ redirect }}" />
        <div>
          <label for="register-name">username: </label>
          <input type="text" id="register-name" name="name" required="" />
        </div>
        <br />
        <div>
          <label for="password">password: </label>
          <input type="password" id="register-password" name="password" required="" />
        </div>
        <a href="javascript:;" onclick="togglepw()">show/hide password</a>
        <br />
        <div>
          <input type="checkbox" id="anon" name="anon" />
          <label for="anon">post anonymously by default </label>
        </div>
        <br />
        <input type="submit" value="register" class="form-submit" />
      </form>
    </fieldset>
  </div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
  function togglepw() {
    const pw = document.getElementById('register-password');

    if (pw.getAttribute('type') === 'password') {
      pw.setAttribute('type', 'text');
    } else {
      pw.setAttribute('type', 'password');
    }
  }
</script>
{% endblock %}

app/templates/message.html
{% extends "index.html" %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h4>{{ title }}</h4>
<p>{{ message }}</p>
{% endblock %}